"""Contract-locked home for the high-score source-authorized vocab-strict path."""

from .certificate_graph import (
    CANONICAL_SOURCE_TEXT_CERTIFICATE_POLICY,
    DIRECTIONAL_CHILD_TO_PARENT_CERTIFICATE,
    ENDPOINT_TITLE_CERTIFICATE,
    LEGACY_ROLE_HINT_CERTIFICATE_POLICY,
    RELATION_ROLE_CERTIFICATE,
    SOURCE_TEXT_CERTIFICATE_GRAPH_CONTRACT,
    SOURCE_TITLE_ENDPOINT_CERTIFICATE,
    SURFACE_ROLE_CERTIFICATE,
    TITLE_ALIAS_CERTIFICATE,
    EvidenceCertificate,
    EvidenceNode,
    SourceTextCertificateGraph,
    build_source_text_certificate_graph,
    certificate_policy_contract,
    normalize_certificate_policy,
)
from .contract import (
    CANONICAL_CLEAN_CONTRACT,
    CANONICAL_CLEAN_METHOD_NAME,
    HIGH_SCORE_CONTRACT,
    HIGH_SCORE_LEGACY_VARIANT,
    PUBLIC_REPORT_ALIAS,
    SOURCE_CERTIFIED_EVIDENCE_COMPLETION_CONTRACT as PAPER_SOURCE_CERTIFIED_EVIDENCE_COMPLETION_CONTRACT,
    SOURCE_CERTIFIED_EVIDENCE_COMPLETION_METHOD_NAME as PAPER_SOURCE_CERTIFIED_EVIDENCE_COMPLETION_METHOD_NAME,
)
from .candidate_expansion import (
    SOURCE_TEXT_CANDIDATE_EXPANSION_CONTRACT,
    SourceTextCandidateExpansion,
    SourceTextCandidateExpansionIndex,
    build_source_text_candidate_expansion_index,
    expand_source_text_candidates,
)
from .retriever import (
    VOCAB_STRICT_RETRIEVER_CONTRACT,
    VocabStrictRetrievalResult,
    source_authorized_vocab_strict_retrieve,
)
from .frontier import (
    SOURCE_FRONTIER_CONTRACT,
    SourceTextFrontier,
    build_source_text_frontier,
)
from .evidence_completion import (
    SOURCE_CERTIFIED_EVIDENCE_COMPLETION_CONTRACT,
    SOURCE_CERTIFIED_EVIDENCE_COMPLETION_METHOD_NAME,
    EvidenceCompletionResult,
    EvidenceCompletionStep,
    EvidenceDemand,
    complete_source_certified_evidence_set,
)
from .active_certificate_graph import (
    ACTIVE_CERTIFICATE_GRAPH_CONTRACT,
    ActiveCertificateEdge,
    ActiveCertificateGraph,
    activate_certificate_edges,
)
from .query_conditioning import QuerySignatures, extract_query_signatures
from .trust_region_repair import (
    TRUST_REGION_REPAIR_CONTRACT,
    TrustRegionRepairResult,
    TrustRegionRepairStep,
    repair_with_active_certificates,
)
from .witness_atoms import (
    WITNESS_ATOM_CONTRACT,
    SourceWarrantedAtom,
    source_warranted_atoms_from_node,
    title_entities_for_doc,
)
from .pipeline import (
    ACTIVE_TRUST_REGION_METHOD_NAME,
    ACTIVE_TRUST_REGION_PIPELINE_CONTRACT,
    END_TO_END_PIPELINE_CONTRACT,
    ActiveTrustRegionPipelineResult,
    SourceCertifiedEvidenceCompletionPipelineResult,
    VocabStrictPipelineResult,
    source_active_trust_region_pipeline_retrieve,
    source_certified_evidence_completion_pipeline_retrieve,
    source_authorized_vocab_strict_pipeline_retrieve,
)
from .query_mentions import query_mentioned_doc_indices

__all__ = [
    "HIGH_SCORE_CONTRACT",
    "HIGH_SCORE_LEGACY_VARIANT",
    "PUBLIC_REPORT_ALIAS",
    "CANONICAL_CLEAN_CONTRACT",
    "CANONICAL_CLEAN_METHOD_NAME",
    "PAPER_SOURCE_CERTIFIED_EVIDENCE_COMPLETION_CONTRACT",
    "PAPER_SOURCE_CERTIFIED_EVIDENCE_COMPLETION_METHOD_NAME",
    "SOURCE_TEXT_CANDIDATE_EXPANSION_CONTRACT",
    "CANONICAL_SOURCE_TEXT_CERTIFICATE_POLICY",
    "LEGACY_ROLE_HINT_CERTIFICATE_POLICY",
    "SourceTextCandidateExpansion",
    "SourceTextCandidateExpansionIndex",
    "build_source_text_candidate_expansion_index",
    "expand_source_text_candidates",
    "DIRECTIONAL_CHILD_TO_PARENT_CERTIFICATE",
    "ENDPOINT_TITLE_CERTIFICATE",
    "RELATION_ROLE_CERTIFICATE",
    "SOURCE_TEXT_CERTIFICATE_GRAPH_CONTRACT",
    "SOURCE_TITLE_ENDPOINT_CERTIFICATE",
    "SURFACE_ROLE_CERTIFICATE",
    "TITLE_ALIAS_CERTIFICATE",
    "EvidenceCertificate",
    "EvidenceNode",
    "SourceTextCertificateGraph",
    "build_source_text_certificate_graph",
    "certificate_policy_contract",
    "normalize_certificate_policy",
    "VOCAB_STRICT_RETRIEVER_CONTRACT",
    "VocabStrictRetrievalResult",
    "source_authorized_vocab_strict_retrieve",
    "SOURCE_FRONTIER_CONTRACT",
    "SourceTextFrontier",
    "build_source_text_frontier",
    "SOURCE_CERTIFIED_EVIDENCE_COMPLETION_CONTRACT",
    "SOURCE_CERTIFIED_EVIDENCE_COMPLETION_METHOD_NAME",
    "EvidenceCompletionResult",
    "EvidenceCompletionStep",
    "EvidenceDemand",
    "complete_source_certified_evidence_set",
    "ACTIVE_CERTIFICATE_GRAPH_CONTRACT",
    "ActiveCertificateEdge",
    "ActiveCertificateGraph",
    "activate_certificate_edges",
    "QuerySignatures",
    "extract_query_signatures",
    "TRUST_REGION_REPAIR_CONTRACT",
    "TrustRegionRepairResult",
    "TrustRegionRepairStep",
    "repair_with_active_certificates",
    "WITNESS_ATOM_CONTRACT",
    "SourceWarrantedAtom",
    "source_warranted_atoms_from_node",
    "title_entities_for_doc",
    "ACTIVE_TRUST_REGION_METHOD_NAME",
    "ACTIVE_TRUST_REGION_PIPELINE_CONTRACT",
    "END_TO_END_PIPELINE_CONTRACT",
    "ActiveTrustRegionPipelineResult",
    "SourceCertifiedEvidenceCompletionPipelineResult",
    "VocabStrictPipelineResult",
    "source_active_trust_region_pipeline_retrieve",
    "source_certified_evidence_completion_pipeline_retrieve",
    "source_authorized_vocab_strict_pipeline_retrieve",
    "query_mentioned_doc_indices",
]
